//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ETEMModel.Models.LogModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UMS_LOGEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UMS_LOGEntities object using the connection string found in the 'UMS_LOGEntities' section of the application configuration file.
        /// </summary>
        public UMS_LOGEntities() : base("name=UMS_LOGEntities", "UMS_LOGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UMS_LOGEntities object.
        /// </summary>
        public UMS_LOGEntities(string connectionString) : base(connectionString, "UMS_LOGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UMS_LOGEntities object.
        /// </summary>
        public UMS_LOGEntities(EntityConnection connection) : base(connection, "UMS_LOGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EventFullLog> EventFullLogs
        {
            get
            {
                if ((_EventFullLogs == null))
                {
                    _EventFullLogs = base.CreateObjectSet<EventFullLog>("EventFullLogs");
                }
                return _EventFullLogs;
            }
        }
        private ObjectSet<EventFullLog> _EventFullLogs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EventFullLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEventFullLogs(EventFullLog eventFullLog)
        {
            base.AddObject("EventFullLogs", eventFullLog);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UMS_LOGModel", Name="EventFullLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventFullLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventFullLog object.
        /// </summary>
        /// <param name="idEventLog">Initial value of the idEventLog property.</param>
        /// <param name="eventDate">Initial value of the EventDate property.</param>
        public static EventFullLog CreateEventFullLog(global::System.Int32 idEventLog, global::System.DateTime eventDate)
        {
            EventFullLog eventFullLog = new EventFullLog();
            eventFullLog.idEventLog = idEventLog;
            eventFullLog.EventDate = eventDate;
            return eventFullLog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEventLog
        {
            get
            {
                return _idEventLog;
            }
            set
            {
                if (_idEventLog != value)
                {
                    OnidEventLogChanging(value);
                    ReportPropertyChanging("idEventLog");
                    _idEventLog = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEventLog");
                    OnidEventLogChanged();
                }
            }
        }
        private global::System.Int32 _idEventLog;
        partial void OnidEventLogChanging(global::System.Int32 value);
        partial void OnidEventLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                OnidUserChanging(value);
                ReportPropertyChanging("idUser");
                _idUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idUser");
                OnidUserChanged();
            }
        }
        private Nullable<global::System.Int32> _idUser;
        partial void OnidUserChanging(Nullable<global::System.Int32> value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventDate
        {
            get
            {
                return _EventDate;
            }
            set
            {
                OnEventDateChanging(value);
                ReportPropertyChanging("EventDate");
                _EventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventDate");
                OnEventDateChanged();
            }
        }
        private global::System.DateTime _EventDate;
        partial void OnEventDateChanging(global::System.DateTime value);
        partial void OnEventDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventMessage
        {
            get
            {
                return _EventMessage;
            }
            set
            {
                OnEventMessageChanging(value);
                ReportPropertyChanging("EventMessage");
                _EventMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventMessage");
                OnEventMessageChanged();
            }
        }
        private global::System.String _EventMessage;
        partial void OnEventMessageChanging(global::System.String value);
        partial void OnEventMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventActionType
        {
            get
            {
                return _EventActionType;
            }
            set
            {
                OnEventActionTypeChanging(value);
                ReportPropertyChanging("EventActionType");
                _EventActionType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventActionType");
                OnEventActionTypeChanged();
            }
        }
        private global::System.String _EventActionType;
        partial void OnEventActionTypeChanging(global::System.String value);
        partial void OnEventActionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EntityActionID
        {
            get
            {
                return _EntityActionID;
            }
            set
            {
                OnEntityActionIDChanging(value);
                ReportPropertyChanging("EntityActionID");
                _EntityActionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EntityActionID");
                OnEntityActionIDChanged();
            }
        }
        private global::System.String _EntityActionID;
        partial void OnEntityActionIDChanging(global::System.String value);
        partial void OnEntityActionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EntityActionName
        {
            get
            {
                return _EntityActionName;
            }
            set
            {
                OnEntityActionNameChanging(value);
                ReportPropertyChanging("EntityActionName");
                _EntityActionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EntityActionName");
                OnEntityActionNameChanged();
            }
        }
        private global::System.String _EntityActionName;
        partial void OnEntityActionNameChanging(global::System.String value);
        partial void OnEntityActionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EntityActionMeaningfulValueJSON
        {
            get
            {
                return _EntityActionMeaningfulValueJSON;
            }
            set
            {
                OnEntityActionMeaningfulValueJSONChanging(value);
                ReportPropertyChanging("EntityActionMeaningfulValueJSON");
                _EntityActionMeaningfulValueJSON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EntityActionMeaningfulValueJSON");
                OnEntityActionMeaningfulValueJSONChanged();
            }
        }
        private global::System.String _EntityActionMeaningfulValueJSON;
        partial void OnEntityActionMeaningfulValueJSONChanging(global::System.String value);
        partial void OnEntityActionMeaningfulValueJSONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersonMakingAction
        {
            get
            {
                return _PersonMakingAction;
            }
            set
            {
                OnPersonMakingActionChanging(value);
                ReportPropertyChanging("PersonMakingAction");
                _PersonMakingAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersonMakingAction");
                OnPersonMakingActionChanged();
            }
        }
        private global::System.String _PersonMakingAction;
        partial void OnPersonMakingActionChanging(global::System.String value);
        partial void OnPersonMakingActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersonSessionID
        {
            get
            {
                return _PersonSessionID;
            }
            set
            {
                OnPersonSessionIDChanging(value);
                ReportPropertyChanging("PersonSessionID");
                _PersonSessionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersonSessionID");
                OnPersonSessionIDChanged();
            }
        }
        private global::System.String _PersonSessionID;
        partial void OnPersonSessionIDChanging(global::System.String value);
        partial void OnPersonSessionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullLogPropertiesXML
        {
            get
            {
                return _FullLogPropertiesXML;
            }
            set
            {
                OnFullLogPropertiesXMLChanging(value);
                ReportPropertyChanging("FullLogPropertiesXML");
                _FullLogPropertiesXML = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullLogPropertiesXML");
                OnFullLogPropertiesXMLChanged();
            }
        }
        private global::System.String _FullLogPropertiesXML;
        partial void OnFullLogPropertiesXMLChanging(global::System.String value);
        partial void OnFullLogPropertiesXMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullLogMeaningfulValuesXML
        {
            get
            {
                return _FullLogMeaningfulValuesXML;
            }
            set
            {
                OnFullLogMeaningfulValuesXMLChanging(value);
                ReportPropertyChanging("FullLogMeaningfulValuesXML");
                _FullLogMeaningfulValuesXML = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullLogMeaningfulValuesXML");
                OnFullLogMeaningfulValuesXMLChanged();
            }
        }
        private global::System.String _FullLogMeaningfulValuesXML;
        partial void OnFullLogMeaningfulValuesXMLChanging(global::System.String value);
        partial void OnFullLogMeaningfulValuesXMLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Page
        {
            get
            {
                return _Page;
            }
            set
            {
                OnPageChanging(value);
                ReportPropertyChanging("Page");
                _Page = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Page");
                OnPageChanged();
            }
        }
        private global::System.String _Page;
        partial void OnPageChanging(global::System.String value);
        partial void OnPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecuritySetting
        {
            get
            {
                return _SecuritySetting;
            }
            set
            {
                OnSecuritySettingChanging(value);
                ReportPropertyChanging("SecuritySetting");
                _SecuritySetting = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecuritySetting");
                OnSecuritySettingChanged();
            }
        }
        private global::System.String _SecuritySetting;
        partial void OnSecuritySettingChanging(global::System.String value);
        partial void OnSecuritySettingChanged();

        #endregion

    
    }

    #endregion

    
}
