// <copyright file="PricingOrderCreate.cs" company="Microsoft">
// Copyright (c) 2015 All Rights Reserved
// </copyright>
// <author>Microsoft</author>
// <date>3/16/2015 9:47:11 AM</date>
// <summary>Implements the PricingOrderCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace Quotes.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PricingOrderCreate Plugin.
    /// </summary>    
    public class PricingOrderCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PricingOrderCreate"/> class.
        /// </summary>
        public PricingOrderCreate()
            : base(typeof(PricingOrderCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "salesorderdetail", new Action<LocalPluginContext>(ExecutePricingOrderCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePricingOrderCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            // TODO: Implement your custom Plug-in business logic.

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;

            Guid quoteDetailID = (Guid)((Entity)context.InputParameters["Target"]).Id;
            ColumnSet set = new ColumnSet();
            set.AllColumns = true;
            var orderDetail = service.Retrieve("salesorderdetail", quoteDetailID, set);
            const decimal minimumValue = 0;
            const decimal minimumRatio = 1;

            if (context.Depth > 1)
            {
                return;
            }
            else
            {
                var priceperunit = (Money)orderDetail["priceperunit"];
                orderDetail["new_specificdiscountpercentage"] = minimumValue;
                orderDetail["new_ratio"] = minimumRatio;
                orderDetail["new_grossannualincome"] = new Money(minimumValue);
                orderDetail["new_gaixratio"] = new Money(minimumValue);
                orderDetail["new_recommendedvalue"] = priceperunit;
                //orderDetail["new_fixedpriceplusratio"] = priceperunit;

                //This sets the current pricing type of the quote product, to the default pricing type of the quote
                var parentOrder = (EntityReference)orderDetail["salesorderid"];

                var quote = service.Retrieve(parentOrder.LogicalName, parentOrder.Id, new ColumnSet(true));

                var pricingType = (OptionSetValue)quote["new_pricingtype"];

                orderDetail["new_pricingtype"] = new OptionSetValue(pricingType.Value);

                service.Update(orderDetail);
            }
        }
    }
}
