//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETEM.ServiceToCreateUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDataView", Namespace="http://schemas.datacontract.org/2004/07/SMCDL.WebServices")]
    [System.SerializableAttribute()]
    public partial class UserDataView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthPlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiplomaNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EGNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMasterLikeBachelorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OKCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentStatusIntCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idStudentStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course {
            get {
                return this.CourseField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseField, value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiplomaNo {
            get {
                return this.DiplomaNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiplomaNoField, value) != true)) {
                    this.DiplomaNoField = value;
                    this.RaisePropertyChanged("DiplomaNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EGN {
            get {
                return this.EGNField;
            }
            set {
                if ((object.ReferenceEquals(this.EGNField, value) != true)) {
                    this.EGNField = value;
                    this.RaisePropertyChanged("EGN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_mail {
            get {
                return this.E_mailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_mailField, value) != true)) {
                    this.E_mailField = value;
                    this.RaisePropertyChanged("E_mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyCode {
            get {
                return this.FacultyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyCodeField, value) != true)) {
                    this.FacultyCodeField = value;
                    this.RaisePropertyChanged("FacultyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacultyNo {
            get {
                return this.FacultyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyNoField, value) != true)) {
                    this.FacultyNoField = value;
                    this.RaisePropertyChanged("FacultyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMasterLikeBachelor {
            get {
                return this.IsMasterLikeBachelorField;
            }
            set {
                if ((this.IsMasterLikeBachelorField.Equals(value) != true)) {
                    this.IsMasterLikeBachelorField = value;
                    this.RaisePropertyChanged("IsMasterLikeBachelor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OKC {
            get {
                return this.OKCField;
            }
            set {
                if ((object.ReferenceEquals(this.OKCField, value) != true)) {
                    this.OKCField = value;
                    this.RaisePropertyChanged("OKC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentName {
            get {
                return this.ParentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentNameField, value) != true)) {
                    this.ParentNameField = value;
                    this.RaisePropertyChanged("ParentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialityName {
            get {
                return this.SpecialityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialityNameField, value) != true)) {
                    this.SpecialityNameField = value;
                    this.RaisePropertyChanged("SpecialityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialty {
            get {
                return this.SpecialtyField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialtyField, value) != true)) {
                    this.SpecialtyField = value;
                    this.RaisePropertyChanged("Specialty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusIDField, value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentStatusIntCode {
            get {
                return this.StudentStatusIntCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentStatusIntCodeField, value) != true)) {
                    this.StudentStatusIntCodeField = value;
                    this.RaisePropertyChanged("StudentStatusIntCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentStatusName {
            get {
                return this.StudentStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentStatusNameField, value) != true)) {
                    this.StudentStatusNameField = value;
                    this.RaisePropertyChanged("StudentStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string University {
            get {
                return this.UniversityField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversityField, value) != true)) {
                    this.UniversityField = value;
                    this.RaisePropertyChanged("University");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSex {
            get {
                return this.UserSexField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSexField, value) != true)) {
                    this.UserSexField = value;
                    this.RaisePropertyChanged("UserSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idStudentStatus {
            get {
                return this.idStudentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.idStudentStatusField, value) != true)) {
                    this.idStudentStatusField = value;
                    this.RaisePropertyChanged("idStudentStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ServiceToCreateUser", ConfigurationName="ServiceToCreateUser.ServiceToCreateUser")]
    public interface ServiceToCreateUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceToCreateUser/ServiceToCreateUser/CreateStudentUserAccount", ReplyAction="ServiceToCreateUser/ServiceToCreateUser/CreateStudentUserAccountResponse")]
        void CreateStudentUserAccount(ETEM.ServiceToCreateUser.UserDataView[] userList, string CourseSchedCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceToCreateUserChannel : ETEM.ServiceToCreateUser.ServiceToCreateUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceToCreateUserClient : System.ServiceModel.ClientBase<ETEM.ServiceToCreateUser.ServiceToCreateUser>, ETEM.ServiceToCreateUser.ServiceToCreateUser {
        
        public ServiceToCreateUserClient() {
        }
        
        public ServiceToCreateUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceToCreateUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceToCreateUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceToCreateUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateStudentUserAccount(ETEM.ServiceToCreateUser.UserDataView[] userList, string CourseSchedCode) {
            base.Channel.CreateStudentUserAccount(userList, CourseSchedCode);
        }
    }
}
