
delete ScholarShipApplication;
delete ScholarShipApplicationCriteria;
delete ScholarShipCount;
delete ScholarShipFamilyRelation;
delete ScholarShipPayment;
delete ScholarShipPaymentBalance;
delete ScholarShipAdmission;