delete ArtModelReportDetail
delete CivilContractArtModelReportLink
delete ArtModelReport
delete ArtModelApplicationDetail
delete ArtModelApplication
delete ArtModelPosing
delete ArtModel
delete ArtModelCharging