delete from HomeState;
delete from FamilyRelation;
delete from CampusApplication;
delete from ScholarShipPaymentBalance;
delete from ScholarShipApplication;
delete from ExamProtocolStudent
delete from ExamProtocolLecturer
delete from ExamProtocol
delete from StudentCourseDiscipline
delete from PreviousEducation
delete from StudentStatusChange
delete from StudentStatus
delete from StudentAdmission;
delete from DiplomaInfo;
delete from Student;
delete from CourseList;
delete from CourseListDetail;
delete from StudentCourseList;
